### PR TITLE
adding start to singularity compose

### PR DESCRIPTION
**Pull request by vsoch**
This pull request is intended to show changes between the develop and (my development) branch. I still need to test this all locally and if that works, on Nero.

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

### CODE REVIEW

**Comment by cleemesser** [comment]
I have started trying this out locally on an ubuntu 16.04 machine. Thank you so much for working on this. I was trying to build this myself and finding it a lot of work.

 -Chris

BTW: My first effort went very far but I was getting a traceback which seems to show an import conflict between newer and older versions of gitdb. I will put together a more format bug report after putting more work into it.

```Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.5/dist-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/usr/local/lib/python3.5/dist-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/usr/local/lib/python3.5/dist-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 584, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 5
77, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/mnt/home2/clee/code/eegml/researchapps-cvat/cvat/urls.py", line 28, in <module>
    path('', include('cvat.apps.engine.urls')),
  File "/usr/local/lib/python3.5/dist-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
 File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/mnt/home2/clee/code/eegml/researchapps-cvat/cvat/apps/engine/urls.py", line 7, in <module>
    from . import views
  File "/mnt/home2/clee/code/eegml/researchapps-cvat/cvat/apps/engine/views.py", line 50, in <module>
    import cvat.apps.dataset_manager.task as DatumaroTask
  File "/mnt/home2/clee/code/eegml/researchapps-cvat/cvat/apps/dataset_manager/task.py", line 24, in <module>
    from datumaro.components.project import Project
  File "/mnt/home2/clee/code/eegml/researchapps-cvat/datumaro/datumaro/components/project.py", line 7, in <module>
    import git
  File "/usr/local/lib/python3.5/dist-packages/git/__init__.py", line 38, in <module>
    from git.exc import *                       # @NoMove @IgnorePep8
  File "/usr/local/lib/python3.5/dist-packages/git/exc.py", line 9, in <module>
    from git.compat import UnicodeMixin, safe_decode, string_types
  File "/usr/local/lib/python3.5/dist-packages/git/compat.py", line 16, in <module>
    from gitdb.utils.compat import (
ImportError: No module named 'gitdb.utils.compat'


```

**Comment by vsoch** [comment]
Of course! I was waiting to test it on Nero before opening PR to the upstream develop branch. Would you like me to do that?

**Comment by cleemesser** [comment]
That would be great.

> Of course! I was waiting to test it on Nero before opening PR to the upstream develop branch. Would you like me to do that?

that would be awesome, as someone who is new to Nero and new to singularity and relatively new to docker, your detailed instructions are extremely helpful.

**Comment by vsoch** [comment]
Great! I'll do that right away. I haven't heard back from my colleague in SRCC so I think probably helping / interacting with you directly is okay.

**Comment by vsoch** [comment]
For gitdb it looks like a realtively new issue https://github.com/gitpython-developers/GitPython/issues/983. And this would impact the entire library, not just the Singularity port, so I think this should be opened up as an issue there. I'd suggest trying the methods suggested in the issue linked (changing the version or using the gitdb2 on pypi) to see if that resolves it.

**Comment by cleemesser** [comment]
It looks like CVAT updated to use GitPython>=3.0.8 14 days ago. I'm not sure if that fixes everything.
I'm still having a basic problem: none of the network services are appearing so the containers are not talking to each other and I can't connect to the web server. 
I'm going to try a simplier example to see if it is a config problem on my computer.

**Comment by vsoch** [comment]
> It looks like CVAT updated to use GitPython>=3.0.8 14 days ago. I'm not sure if that fixes everything. 

That would do it!

> I'm still having a basic problem: none of the network services are appearing so the containers are not talking to each other and I can't connect to the web server. I'm going to try a simplier example to see if it is a config problem on my computer.

There could also be issue with the version of Singularity you are using - I'm fairly certain everything wasn't working until after 3.2.1. I would first try out a dummy case, and actually use the exact case that I used to report this same error when singularity was new (my containers didn't talk to one another either!)

https://github.com/sylabs/singularity/pull/3771#issuecomment-504414459

When you get that test case working, then you can be sure it's not a singularity version issue.

**Comment by cleemesser** [comment]
Thanks. I tried my original simple web server at that works. I also tried the command line test case where the two singularity containers ping each other works (sylabs/singularity#3771). That works fine as well. 

I compiled singularity from source with default arguments 6 weeks ago at version 3.5.2 and installed it as root so from what I could tell I should have full capabilities.

**Comment by vsoch** [comment]
okay great! That narrows down the issues then. Are you still seeing the error about the version about `gitdb` (e.g., if you do `singularity-compose logs` or target a specific container `singularity-compose logs cvatui`. If there are any issues with starting up, then likely the container instances aren't running properly and cannot talk to one another. Do you want to open a new issue on the repository to start fresh with the errors that you see, and we will go from there? I will first want to re-build and see if I can reproduce your errors. I also have the first containers I built on another computer (not with me now) if we want to check any versions of gitdb, etc.

**Pull request merged**
